import one_hot library

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

Datasets or sentences

In [ ]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

vocabulary size in 10000

In [ ]:
##vocab_size means actually what is the size of dictonary
voc_size = 10000

one hot representation

In [ ]:
##coverting sentences into one hot representation 
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)
##print one hot representation to provide the index of each word in sentences from dictonary(vocab_size).

[[4020, 5152, 6419, 7612], [4020, 5152, 6419, 8971], [4020, 5402, 6419, 563], [7800, 1285, 1480, 8207, 4111], [7800, 1285, 1480, 8207, 8546], [4866, 4020, 1667, 6419, 16], [1613, 936, 3427, 8207]]


import library for embedding

In [ ]:
import numpy as np
from tensorflow.keras.layers import Embedding   ##whatever one hot representaion we have passing through embedding layers in keras to form a embedding matrix
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential  ##to create a embedding layer

In [ ]:
sent_length = 8  ##length of sentecese what we want 
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen= sent_length)
print(embedded_docs)

[[   0    0    0    0 4020 5152 6419 7612]
 [   0    0    0    0 4020 5152 6419 8971]
 [   0    0    0    0 4020 5402 6419  563]
 [   0    0    0 7800 1285 1480 8207 4111]
 [   0    0    0 7800 1285 1480 8207 8546]
 [   0    0    0 4866 4020 1667 6419   16]
 [   0    0    0    0 1613  936 3427 8207]]


In [ ]:
dim = 10  ##giving value of feature value or dimension 

create and compile the embedding model

In [ ]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile('adam', 'mse')   ##mean squared error

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

[[[ 0.02544329 -0.02567418  0.00140526 -0.02701032 -0.02897974
    0.04739653 -0.02695067 -0.01434957 -0.0427057  -0.02353166]
  [ 0.02544329 -0.02567418  0.00140526 -0.02701032 -0.02897974
    0.04739653 -0.02695067 -0.01434957 -0.0427057  -0.02353166]
  [ 0.02544329 -0.02567418  0.00140526 -0.02701032 -0.02897974
    0.04739653 -0.02695067 -0.01434957 -0.0427057  -0.02353166]
  [ 0.02544329 -0.02567418  0.00140526 -0.02701032 -0.02897974
    0.04739653 -0.02695067 -0.01434957 -0.0427057  -0.02353166]
  [-0.03259543 -0.0289857  -0.04239798 -0.00786824 -0.03455605
    0.02364257 -0.04435777  0.03780064 -0.0107108   0.03750587]
  [ 0.04547947 -0.03506346  0.03379459  0.01610159  0.00182837
   -0.00582638  0.00425176  0.04637197  0.03089442 -0.02183052]
  [-0.04138124  0.00198827 -0.04453998 -0.03033475 -0.04374857
    0.04265083 -0.00698382 -0.03213228  0.01594694 -0.00515705]
  [-0.02715267  0.01656504 -0.0019403  -0.04829356  0.01356304
   -0.02899362  0.02899361  0.02626107 -0.007347

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 4020, 5152, 6419, 7612], dtype=int32)

In [ ]:
print(model.predict(embedded_docs[0]))

[[[ 0.02544329 -0.02567418  0.00140526 -0.02701032 -0.02897974
    0.04739653 -0.02695067 -0.01434957 -0.0427057  -0.02353166]]

 [[ 0.02544329 -0.02567418  0.00140526 -0.02701032 -0.02897974
    0.04739653 -0.02695067 -0.01434957 -0.0427057  -0.02353166]]

 [[ 0.02544329 -0.02567418  0.00140526 -0.02701032 -0.02897974
    0.04739653 -0.02695067 -0.01434957 -0.0427057  -0.02353166]]

 [[ 0.02544329 -0.02567418  0.00140526 -0.02701032 -0.02897974
    0.04739653 -0.02695067 -0.01434957 -0.0427057  -0.02353166]]

 [[-0.03259543 -0.0289857  -0.04239798 -0.00786824 -0.03455605
    0.02364257 -0.04435777  0.03780064 -0.0107108   0.03750587]]

 [[ 0.04547947 -0.03506346  0.03379459  0.01610159  0.00182837
   -0.00582638  0.00425176  0.04637197  0.03089442 -0.02183052]]

 [[-0.04138124  0.00198827 -0.04453998 -0.03033475 -0.04374857
    0.04265083 -0.00698382 -0.03213228  0.01594694 -0.00515705]]

 [[-0.02715267  0.01656504 -0.0019403  -0.04829356  0.01356304
   -0.02899362  0.02899361  0.0262