In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/drive/MyDrive/train.csv')
df.head(10)

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1
5   5  ...     0
6   6  ...     1
7   7  ...     0
8   8  ...     0
9   9  ...     0

[10 rows x 5 columns]

In [5]:
df['author'].fillna

<bound method Series.fillna of 0                                    Darrell Lucus
1                                  Daniel J. Flynn
2                               Consortiumnews.com
3                                  Jessica Purkiss
4                                   Howard Portnoy
                           ...                    
20795                                Jerome Hudson
20796                             Benjamin Hoffman
20797    Michael J. de la Merced and Rachel Abrams
20798                                  Alex Ansary
20799                                David Swanson
Name: author, Length: 20800, dtype: object>

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
x = df.drop('label', axis = 1)
x.head(10)

id  ...                                               text
0   0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1   1  ...  Ever get the feeling your life circles the rou...
2   2  ...  Why the Truth Might Get You Fired October 29, ...
3   3  ...  Videos 15 Civilians Killed In Single US Airstr...
4   4  ...  Print \nAn Iranian woman has been sentenced to...
5   5  ...  In these trying times, Jackie Mason is the Voi...
6   6  ...  Ever wonder how Britain’s most iconic pop pian...
7   7  ...  PARIS  —   France chose an idealistic, traditi...
8   8  ...  Donald J. Trump is scheduled to make a highly ...
9   9  ...  A week before Michael T. Flynn resigned as nat...

[10 rows x 4 columns]

In [ ]:
x['author'][6]

nan

In [8]:
y = df['label']
y

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 20800, dtype: int64

In [ ]:
df.shape

(20800, 5)

In [ ]:
df = df.dropna()

In [ ]:
df.shape

(18285, 5)

In [ ]:
df.head(10)

id  ... label
0    0  ...     1
1    1  ...     0
2    2  ...     1
3    3  ...     1
4    4  ...     1
5    5  ...     0
7    7  ...     0
9    9  ...     0
10  10  ...     0
11  11  ...     0

[10 rows x 5 columns]

In [10]:
messages = df.copy()

In [ ]:
messages.reset_index(inplace = True)

In [ ]:
messages.head(10)

index  id  ...                                               text label
0      0   0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...     1
1      1   1  ...  Ever get the feeling your life circles the rou...     0
2      2   2  ...  Why the Truth Might Get You Fired October 29, ...     1
3      3   3  ...  Videos 15 Civilians Killed In Single US Airstr...     1
4      4   4  ...  Print \nAn Iranian woman has been sentenced to...     1
5      5   5  ...  In these trying times, Jackie Mason is the Voi...     0
6      7   7  ...  PARIS  —   France chose an idealistic, traditi...     0
7      9   9  ...  A week before Michael T. Flynn resigned as nat...     0
8     10  10  ...  Organizing for Action, the activist group that...     0
9     11  11  ...  The BBC produced spoof on the “Real Housewives...     0

[10 rows x 6 columns]

In [11]:
y = messages['label']

In [ ]:
messages['author'][6]

'Alissa J. Rubin'

In [ ]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
import re

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
stemmer = PorterStemmer()
wordnet = WordNetLemmatizer()

In [ ]:
corpus = []
for x in range(len(messages)):
  review = re.sub('[^a-zA-Z]', ' ', messages['title'][x])
  review = review.lower()
  review = review.split()
  review = [wordnet.lemmatize(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [13]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [ ]:
corpus

['house dem aide even see comey letter jason chaffetz tweeted',
 'flynn hillary clinton big woman campus breitbart',
 'truth might get fired',
 'civilian killed single u airstrike identified',
 'iranian woman jailed fictional unpublished story woman stoned death adultery',
 'jackie mason hollywood would love trump bombed north korea lack trans bathroom exclusive video breitbart',
 'beno hamon win french socialist party presidential nomination new york time',
 'back channel plan ukraine russia courtesy trump associate new york time',
 'obama organizing action partner soros linked indivisible disrupt trump agenda',
 'bbc comedy sketch real housewife isi cause outrage',
 'russian researcher discover secret nazi military base treasure hunter arctic photo',
 'u official see link trump russia',
 'yes paid government troll social medium blog forum website',
 'major league soccer argentine find home success new york time',
 'well fargo chief abruptly step new york time',
 'anonymous donor pay 

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
voc_size = 5000
onehot_repr = [one_hot(words, voc_size) for words in corpus]
onehot_repr

[[4766, 4520, 2003, 404, 4455, 4338, 1109, 95, 4239, 2625],
 [4309, 2355, 4416, 708, 3747, 2016, 416],
 [1751, 333, 4876, 1175],
 [851, 4601, 660, 3123, 3682, 3524],
 [906, 3747, 1036, 406, 2285, 4236, 3747, 3120, 734, 3208],
 [4035,
  2513,
  4812,
  1413,
  2778,
  92,
  3473,
  447,
  573,
  4370,
  42,
  2382,
  455,
  2280,
  416],
 [2230, 2759, 3132, 3207, 1309, 2894, 193, 819, 1553, 2228, 4519],
 [4161, 4076, 243, 3833, 1308, 1834, 92, 2578, 1553, 2228, 4519],
 [2001, 1932, 3586, 512, 439, 815, 1506, 1873, 92, 4729],
 [578, 632, 4929, 4347, 43, 1862, 4387, 3640],
 [3988, 2256, 1731, 212, 2744, 3712, 3808, 1849, 4620, 286, 291],
 [3123, 2888, 4455, 3363, 92, 1308],
 [2482, 4702, 1728, 2099, 4398, 247, 14, 2986, 2146],
 [1572, 2436, 2051, 3836, 3408, 1998, 2812, 1553, 2228, 4519],
 [3021, 324, 4840, 507, 2189, 1553, 2228, 4519],
 [3359, 2794, 1093, 2002, 1841, 4675, 2536, 3673, 3644, 4703],
 [4649, 1606, 2355],
 [1826, 4516, 1365, 4580, 92, 3862, 2686, 416],
 [2230, 2988, 4416, 32

In [ ]:
corpus[5]

'jackie mason hollywood would love trump bombed north korea lack trans bathroom exclusive video breitbart'

In [ ]:
onehot_repr[5]

[4035,
 2513,
 4812,
 1413,
 2778,
 92,
 3473,
 447,
 573,
 4370,
 42,
 2382,
 455,
 2280,
 416]

In [ ]:
sent_length = 20
embedded_docs = pad_sequences(onehot_repr, padding = 'post', maxlen = sent_length)
embedded_docs

array([[4766, 4520, 2003, ...,    0,    0,    0],
       [4309, 2355, 4416, ...,    0,    0,    0],
       [1751,  333, 4876, ...,    0,    0,    0],
       ...,
       [ 447, 2707, 3419, ...,    0,    0,    0],
       [2550, 1308,  594, ...,    0,    0,    0],
       [2096, 4176, 3232, ...,    0,    0,    0]], dtype=int32)

In [ ]:
embedded_docs[0]

array([4766, 4520, 2003,  404, 4455, 4338, 1109,   95, 4239, 2625,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
len(embedded_docs)

18285

In [ ]:
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))
model.add(LSTM(100))
model.add(Dense(1, activation = 'sigmoid'))

In [ ]:
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [ ]:
len(embedded_docs), y.shape

(18285, (18285,))

In [ ]:
x_final = np.array(embedded_docs)
y_final = np.array(y)

In [ ]:
x_final.shape, y_final.shape

((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_final, y_final, test_size = 0.33, random_state = 42)

In [ ]:
model.fit(x_train, y_train, validation_data = (x_test, y_test), epochs = 10, batch_size = 64)

Epoch 1/10
192/192 [==============================] - 9s 37ms/step - loss: 0.3102 - accuracy: 0.8457 - val_loss: 0.2006 - val_accuracy: 0.9160
Epoch 2/10
192/192 [==============================] - 7s 34ms/step - loss: 0.1289 - accuracy: 0.9544 - val_loss: 0.2144 - val_accuracy: 0.9183
Epoch 3/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0888 - accuracy: 0.9708 - val_loss: 0.2134 - val_accuracy: 0.9079
Epoch 4/10
192/192 [==============================] - 6s 34ms/step - loss: 0.0594 - accuracy: 0.9822 - val_loss: 0.2502 - val_accuracy: 0.9157
Epoch 5/10
192/192 [==============================] - 6s 34ms/step - loss: 0.0434 - accuracy: 0.9873 - val_loss: 0.4012 - val_accuracy: 0.9019
Epoch 6/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0361 - accuracy: 0.9896 - val_loss: 0.3677 - val_accuracy: 0.9074
Epoch 7/10
192/192 [==============================] - 6s 34ms/step - loss: 0.0254 - accuracy: 0.9923 - val_loss: 0.3724 - val_accuracy: 0.9052

In [ ]:
y_pred = model.predict(x_test)
classes_x = np.argmax(y_pred, axis=1)

In [ ]:
y_pred = (y_pred).astype(int)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
confusion_matrix(y_test, y_pred)

array([[3419,    0],
       [2616,    0]])

In [ ]:
accuracy_score(y_test, y_pred)

0.5665285832642917

In [ ]:
y_test.shape, y_pred.shape

((6035,), (6035, 1))

In [ ]:
x_test.shape

(6035, 20)